# name: Build release version of document

# on:
#   push:
#     tags:
#       - 'r[0-9]+.[0-9]+.[0-9]+'

# permissions:
#   contents: write  # without this line the release job fails

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up LaTeX environment
#         run: sudo apt-get update && sudo apt-get install -y texlive texlive-lang-german texlive-latex-extra biber

#       - name: Compile LaTeX document
#         run: make release

#       - name: Upload PDF as artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: build-artifact
#           path: ./main.pdf

#   release:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Download build artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: build-artifact
#           path: ./

#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           body: |
#             Changes in this Release
#             - First Change
#             - Second Change
#           draft: false
#           prerelease: false

#       - name: Upload PDF to Release
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./main.pdf
#           asset_name: expose_${{  github.ref_name }}.pdf
#           asset_content_type: application/pdf
